### ISSUE TITLE
(DG KR) Finalize Open / Closed Issues Table in sdpi-supplement-issues.adoc

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#232]

**Comment by d-gregorczyk** [comment]
To be honest, I do not see a reason to have this chapter as it is - at least I don't feel like maintaining this tremendously growing list and moving issues back and forth. Is this explicitly required by IHE? I'd rather recommend to add a changelog list to the document or to a seperate changelog.md file similar to how it is done here: https://gitlab.com/sdc-suite/sdc-ri/-/blob/develop/CHANGELOG.md ; based on: https://keepachangelog.com/en/1.0.0/

This allows for readers of the spec to track added, deleted and modified chapters throughout the document's lifecycle. A Github reference number can be added to changelog entries for linkage to the actual github issues - where the details should reside. Changelog entries should not be longer than a single sentence (see also the linked changelog above).

Moreover, for any 1.0 of something there is no need to have a changelog - it's the baseline document. Only if we begin changing the document because of defects, change requests or obsoletions, we should gradually fill in the space of the chaneglog.

Strong disagree? Any thoughts?

**Comment by d-gregorczyk** [comment]
PS: We could add a pull request template to require people adding changelog entries before merging: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by ToddCooper** [comment]
> To be honest, I do not see a reason to have this chapter as it is - at least I don't feel like maintaining this tremendously growing list and moving issues back and forth. Is this explicitly required by IHE? I'd rather recommend to add a changelog list to the document or to a seperate changelog.md file similar to how it is done here: https://gitlab.com/sdc-suite/sdc-ri/-/blob/develop/CHANGELOG.md ; based on: https://keepachangelog.com/en/1.0.0/
> 
> This allows for readers of the spec to track added, deleted and modified chapters throughout the document's lifecycle. A Github reference number can be added to changelog entries for linkage to the actual github issues - where the details should reside. Changelog entries should not be longer than a single sentence (see also the linked changelog above).
> 
> Moreover, for any 1.0 of something there is no need to have a changelog - it's the baseline document. Only if we begin changing document 1.0 because of defects, change requests or obsoletions, we should gradually fill in the space of the chaneglog.
> 
> Strong disagree? Any thoughts?

**Comment by ToddCooper** [comment]
This was transferred to IHE/DEV.SDPi#20
