### ISSUE TITLE
Adapted System Function Contribution definition changes the meaning of original PKP term

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#250]
## Section Number

Volume 0, Appendix D

## Priority

Low

## Issue

The original definition uses the term SDC PARTICIPANT that implies conformity to all three core standards and not just BICEPS (As far as I know, there is no definition of a BICEPS PARTICIPANT in the Core standards). 

## Proposed Change

Replace with something like: Function of an SDC PARTICIPANT that contributes to a CLINICAL FUNCTION provided by two or more SDC PARTICIPANTs that are  part of an SDC SYSTEM.

**Comment by ToddCooper** [comment]
A more general question is the use of "BICEPS Participant" throughout the SDPi specification volumes.  Note that "BICEPS Participant Model" is called out in -10207, "Participant" is defined and used in -10207 , SDC Participant is defined in -20701.  We need to be clear in our use within the SDPi specifications and capture this properly in the TF-0:  Appendix D.

**Comment by ToddCooper** [comment]
@AnnaFeiler  - is your proposal the final wording of the -10700 document?  I looked and the wording used was what I had in my version of the -10700.  

NOTE:  If I adapted your wording, it would replace "SDC PARTICIPANT" with "SOMDS Participant", and "SDC SYSTEM" with "SOMDS", since this is not SDC but SDPi and these definitions have been adapted for use in our context which may be by definition, a profiled and extended version of the base SDC standards, including PKPs - though mostly the core.

In our discussion today, you mentioned that the updated wording ensured that all (3) core SDC standards were included, and you are afraid that if I used "BICEPS PARTICIPANT" it would imply only the BICEPS standard.  Yes?  Would my adapted wording of your proposed change be agreeable?

**Comment by AnnaFeiler** [comment]
@ToddCooper : the wording is adapted from the last draft I had for the -10700 document. Replacing SDC Participant with SOMDS Participant is fine with me and would adress my concern, since it includes all the core standards. 

So something like: "Function of a SOMDS Participant that contributes to a CLINICAL FUNCTION provided by a SOMDS." would be great.

**Comment by ToddCooper** [comment]
"v3" branch text updated per suggestion.
