### ISSUE TITLE
Use Case Feature 1: Synchronized Time Across Devices (STAD) remarks

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#253]
## Section Number

Volume 1, Appendix C.2. Use Case Feature 1: Synchronized Time Across Devices (STAD)

## Priority

high

## Issue

_C.2.1: Could we put some more information here to stress the benefit of this use case (examples: all devices at the same workplace use the same time as a precondition for remote viewing, export to a gateway for consistent documentation…)?_ was moved to #317

C.2.4.2 and following sections: Broken links and a general question: Do we want to allow manually changing the time? I know BICEPS does, but I don’t think it is a good idea to do this here (This question caused the high priority). This could very easily destroy all interoperability in our systems. 

C.2.4.3 Did we define transactions for this behavior? 

## Proposed Change

See issue description

**Comment by ToddCooper** [comment]
Note:  From TF-1:10.4.1.3 Ensuring Time Synchronization note:

> TODO: No time sync service identified in 11073 SDC core; include only in the SDPi-P section …​ as a requirement to use NTP?; reference resolution of TS Service, MD LAN, in glossary entries

This STAD use case requirement is addressed by the SDPi-P use case requirements section (_10.4.2.1 Synchronized Time Across Devices (STAD)_).

So the question is how to to specify the use of NTP in this specification.  @d-gregorczyk ?

**Comment by AnnaFeiler** [comment]
@d-gregorczyk : I've moved the C.2.1 comment to another ticket but I'd really like to discuss making ntp mandatory and removing the option to manually set the time.

**Comment by AnnaFeiler** [comment]
Follow up comment fron a discussion with @d-gregorczyk: 
use case C.2.4.2 should be removed and replaced by a requirement, that explicitly forbids us to change the time manually if a time server is available. 

C.2.4.3 and C.2.4.4. are impossible since devices don't have the capability to synchronise their time without a time server. They need to be removed.

**Comment by ToddCooper** [comment]
@AnnaFeiler  -- as discussed on today's Friday call (03.02.2023), the SDPi-P profile is dependent on the IHE Consistent Time (CT) profile which requires use of NTP.  This is the case for ALL IHE profiles, including all DEV profiles.  In Connectathons, it is the first profile that is tested for all participating systems, especially for any that have security!  

There is a section already allocated in the SDPi-P profile that indicates how the profile implements the requirements from this use case.  

@kenjfuchs  -- Please take a look at Anna's recommendations and make sure that what I am saying matches reality and what we need to do in this specification.

**Comment by kenjfuchs** [comment]
Currently the scenario where the time is changed manually at a device is out of scope for SDPi 1.0.
The decision to require an NTP server should be discussed more widely.  For example in the current Draeger Infinity/OneNet network the capability of changing the time manually has been implemented since one of the design objectives of the network was to be able to operate without a time master (pure peer to peer).  What should we do in a small network, for example in an OR room, where we just have a few devices communicating with each other?  Or do we require all SDC based implementations to be interconnected to an enterprise network in some fashion and rely on an NTP service to always be present?  What happens if there is a failure to connect with an NTP service?

**Comment by klotzt-draeger** [comment]
Yes, NTP is mandatory, SDC cannot work without it. No manual time change shoudl be allowed.

(For small "island" setups we can still run the NTP server on one of the components but that doesnt change the fact that it's NTP as defined in IHE-CT profile).

**Comment by kenjfuchs** [comment]
Hi Tobias,
Thanks for the clarification.👍

Should we have mitigations if the NTP server is not accessible for
some reason due to a temporary failure?
The simplest approach would be for the devices to continue to communicate
time based on their internal clocks which tend to be pretty accurate for
moderate lengths of time.
However, what if the user wants to add a device to a network during a
temporary failure?
Does the device wait until the time service is available to participate on
the network? Or do we recommend some other behavior?
Ken

**Comment by ToddCooper** [comment]
All I can say, Tobias, is that this warms Old Man Cooper's heart 😎

**Comment by ToddCooper** [comment]
> Hi Tobias, Thanks for the clarification.👍 Should we have mitigations if the NTP server is not accessible for some reason due to a temporary failure? The simplest approach would be for the devices to continue to communicate time based on their internal clocks which tend to be pretty accurate for moderate lengths of time. However, what if the user wants to add a device to a network during a temporary failure? Does the device wait until the time service is available to participate on the network? Or do we recommend some other behavior? Ken

@kenjfuchs  - Perhaps just adding a comment in the SES section of SDPi-P around the need to do risk management for time sync "if the user wants to add a device to a network during temporary failures" etc.  

IOW - That is the purpose of these SES blocks, provide guidance to implementers about risks and mitigations that should be considered when developing and deploying solutions.

At a Use Case level, we have the general proviso of "Do it in a safe, effective and secure way" and then can specialize that in Use Case specifications when appropriate for (a) well known cases, and (b) when we have mitigations baked into the specifications.  

Of course, this is what the PKPs are intended to address (at least for safety) ... so is this question actually relevant to the base PKP?

**Comment by kenjfuchs** [comment]
As far as the use cases are concerned, I can mark the scenarios that deal
with Time Service failures of one kind or another as future topics and
leave them for SDPI 1.x.

I was also wondering whether this was something one of the PKPs should
address.

Ken

**Comment by kenjfuchs** [comment]
Just looked at the document, and these scenarios are already marked as out
of scope.
I changed the proposed action to ???TBD???, so it is clear we will need to
fill in something in the future.
Ken

**Comment by AnnaFeiler** [comment]
@kenjfuchs: I agree, that Time Service failures need to be postponed. For the moment: 

C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a <a href="#acronym_ts_service">TS Service</a> and a second device’s time setting is changed manually - delete since that is forbidden

C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a <a href="#acronym_ts_service">TS Service</a> and a second device’s time setting is changed manually - keep the version note that this is out of scope, remove the "given, when, then" part since the "then"  is impossible from a technical point of view. If the reference is still broken in your version, please also fix the reference

C.2.4.4 Scenario: STAD 1.4 - Device is connected to network but cannot connect to a Time Source server and a second device’s time setting is changed manually - needs to be deleted since it is technically impossible. 

I've added new tickets to capture our discussions on the error handling, as well as adding a requirement that C.2.4.2 is forbidden (see IHE/DEV.SDPi#31 and IHE/DEV.SDPi#30 ). Please do not add new tbd or todo notes to the document! We are trying to get rid of those for the review phase.

**Comment by kenjfuchs** [comment]
See my comments below:

C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a TS
Service
<https://mail.google.com/mail/u/0/#m_8823405122495400246_acronym_ts_service>
and
a second device’s time setting is changed manually - delete since that is
forbidden

> I would prefer to leave the scenario in and document that the ability to
change the time manually is disabled when the device is on an MD LAN with a
TS.

> We also need a statement in the Profile that this is the case...

C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a TS
Service
<https://mail.google.com/mail/u/0/#m_8823405122495400246_acronym_ts_service>
and
a second device’s time setting is changed manually - keep the version note
that this is out of scope, remove the "given, when, then" part since the
"then" is impossible from a technical point of view. If the reference is
still broken in your version, please also fix the reference

>This is a repeat of the previous...  Did you mean to talk about C.2.4.3?

C.2.4.4 Scenario: STAD 1.4 - Device is connected to the network but cannot
connect to a Time Source server and a second device’s time setting is
changed manually - needs to be deleted since it is technically impossible.

> I don't understand why this is impossible - this one is a case of a TS
failure which we are agreeing to postpone.

> In any case, in this scenario the connected device will do nothing.


I have removed the TBDs from the Use Cases...

Ken

**Comment by AnnaFeiler** [comment]
@kenjfuchs _Added another round of comments_

C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a TS
Service
<https://mail.google.com/mail/u/0/#m_8823405122495400246_acronym_ts_service>
and
a second device’s time setting is changed manually - delete since that is
forbidden
 I would prefer to leave the scenario in and document that the ability to
change the time manually is disabled when the device is on an MD LAN with a
TS.
 We also need a statement in the Profile that this is the case...

_That is kind of redundant, since the first device cannot know about the second device's time settings. If you feel that makes the use case more easy to understand, we can also leave it in and document that manual time changes are disabled. Issue IHE/DEV.SDPi#30  takes care of adding a statement..._


C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a TS
Service
<https://mail.google.com/mail/u/0/#m_8823405122495400246_acronym_ts_service>
and
a second device’s time setting is changed manually - keep the version note
that this is out of scope, remove the "given, when, then" part since the
"then" is impossible from a technical point of view. If the reference is
still broken in your version, please also fix the reference
This is a repeat of the previous...  Did you mean to talk about C.2.4.3?
_yes_ 

C.2.4.4 Scenario: STAD 1.4 - Device is connected to the network but cannot
connect to a Time Source server and a second device’s time setting is
changed manually - needs to be deleted since it is technically impossible.
 I don't understand why this is impossible - this one is a case of a TS
failure which we are agreeing to postpone.
 In any case, in this scenario the connected device will do nothing.
_The devices on the network cannot know about the time, that was manually changed on one device if that device is not a TS (Which would invalidate the precondition)_

I have removed the TBDs from the Use Cases...
_Thank you!_

**Comment by kenjfuchs** [comment]
OK - I've made a number of changes to the scenarios.
Removed any mention of a second device changing its clock since this will
not affect any other devices.

Did you have an issue with C.2.4.3?

Ken

**Comment by ToddCooper** [comment]
Issue resolved with PR IHE/sdpi-fhir#350
