### ISSUE TITLE
Why do we need device specialization content modules?

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#264]
## Section Number

Volume 3, chapter 8.7 Device specialization content modules

## Priority

Medium

## Issue

There will be device specializations as part of IEEE 11073 SDC. Some are already in place. Why do we add them here?  

## Proposed Change

Delete this chapter as it is mostly a placeholder anyways. If we really need this and the SDC specializations are insufficient, add it later on.

**Comment by ToddCooper** [comment]
1) for PoCD devices, it is not clear when ... IF ... these will actually turn into IEEE 11073 device specialization standards
          (this is a historic perspective, given decades of focused effort and nothing to show)

because of that 

2) IHE DEV TF-3 has had device specialization content modules since its first version in 2006; this SDPi 1.0 provides a simple update to existing content; without it, we would only have non-BICEPS specializations, which would be misleading

3) We can and should add device-specific value sets & containment trees to enable more rigorous testing of implementations (e.g., using NIST tools) - intent is to release with SDPi, XML model files that can be used for specialization verification

4) Without them, semantic interoperability would be severely crippled, potentially resulting in a significant, negative impact on adoption and even perception of the specification.

5) Eventually, we will have device and / or clinical function focused profiles - which will leverage these semantic content modules, in TF-3
     NOTE:  Having device specialization profiles has a huge impact on the RFP/RFQ purchasing process
