### ISSUE TITLE
tf-1 Figure 2.3.1-1 Text & Arrows

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#276]
## Section Number

Figure 2.3.1-1. IHE SDPi Profiles & Foundational Standards

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

"Connectivity" is not in the name of SDPi-P as described below. Propose to remove it from the figure box (to read "SDPi Plug-and-Trust").

In addition, since the arrows point in most cases to the basis of a given layer, it would be appropriate to flip the arrows of the 3 PKPs (R, A, xC) to point up to -P.

## Proposed Change

See issue description.

**Comment by ToddCooper** [comment]
"Connectivity" is mentioned in the subsequent descriptive text.  In this diagram, it is not intended to define the acronym "SDPi" but to describe the general concept and functionality of this profile.  Though "Plug-and-Trust" may connote a "connectivity" scope to some, including it has proved very helpful to understanding the profile's capabilities.  

The arrows from profiles or the dotted box grouping indicate referential direction (e.g., the SDPi-A references the specifications in the ACM profile).  In order to limit the complexity of the diagram, "PKP" was included in a single box - though there are in effect (4) separate standards.  In this diagram, the only PKP's that are included are the (3) that are built on the base of the 11073-10700 Base PKP.  The intent is that the three profiles support "medical" functionality; whereas, the SDPi-P profile supports general connectivity of healthcare systems, and it is TBD whether and how much of -10700 will apply to that profile.  It WILL apply fully to the medical-ready -R, -A, -xC profiles.  

Finally, the arrow pointing from the Big Blue Box to the SDC Core Standards implies that all the profiles reference the SDC Core, and thus the arrow directionality as specified  above.  

Comment is noted but let's see how it resonates with the Public Comment review and Trial Implementation version.  If there is confusion voiced, then the diagram can definitely be updated accordingly.

**Comment by JavierEspina** [comment]
> "Connectivity" is mentioned in the subsequent descriptive text. In this diagram, it is not intended to define the acronym "SDPi" but to describe the general concept and functionality of this profile. Though "Plug-and-Trust" may connote a "connectivity" scope to some, including it has proved very helpful to understanding the profile's capabilities.
> 
> The arrows from profiles or the dotted box grouping indicate referential direction (e.g., the SDPi-A references the specifications in the ACM profile). In order to limit the complexity of the diagram, "PKP" was included in a single box - though there are in effect (4) separate standards. In this diagram, the only PKP's that are included are the (3) that are built on the base of the 11073-10700 Base PKP. The intent is that the three profiles support "medical" functionality; whereas, the SDPi-P profile supports general connectivity of healthcare systems, and it is TBD whether and how much of -10700 will apply to that profile. It WILL apply fully to the medical-ready -R, -A, -xC profiles.
> 
> Finally, the arrow pointing from the Big Blue Box to the SDC Core Standards implies that all the profiles reference the SDC Core, and thus the arrow directionality as specified above.
> 
> Comment is noted but let's see how it resonates with the Public Comment review and Trial Implementation version. If there is confusion voiced, then the diagram can definitely be updated accordingly.

Thx Todd. I agree with your reasoning on "connectivity". And you're right that the PKP are in the green box. That was a mistake I made in describing the second issue. The proper way to describe the issue would have been:  **it would be appropriate to flip the white arrows of the 3 "medical" SDPi profiles (-R, -A, -xC) to point up to SDPi-P"**

**Comment by ToddCooper** [comment]
Update WHITE arrows to point to SDPi-P

**Comment by ToddCooper** [comment]
Figure updated in branch:  https://github.com/IHE/sdpi-fhir/tree/sdpi-1.0-dev-internal-review-v3
