### ISSUE TITLE
Collected Comments on TF-2 Sections B.4

### ISSUE THREAD

**Issue by MartinKasp** [IHE/sdpi-fhir#286]
First of all, I like to repress my deep appreciation for the work that has been done in this section. **Great job!** Thus, please do not misunderstand the number of comments I made. 

Please find my comments in the attached PDF file. Yellow highlights are normal comments. The green color indicates answers to questions.

PS: Please not that I am not an HL7 expert. Thus, some questions/comments might be stupid ^^ However, this might make to a representative reader coming from the SDC devices part and using the document to start with HL7 implementations. Thus, even stupid comments light lead to senseful notes or explanations 

[_TF2_Appendix_B4 - sdpi-supplement.html-comments_MK_v01-.pdf](https://github.com/IHE/sdpi-fhir/files/10464605/_TF2_Appendix_B4.-.sdpi-supplement.html-comments_MK_v01-.pdf)

**Comment by PeterKranich** [comment]
According to Martin's comments, the following changes are proposed:

- Currently, the ACM and DEC gateway section fully describe the mapping requirements without jumping back and forth to other sections in the document. However, the issue is that common requirements are duplicated with the same requirement id in both section which leds to some problems. So, we need to move the common requirment to the common gateway section.
- We agreed in the Alert-PKP working group that we need a unique alert event identifier from the alert source. This shall be a GUID. OBR requirements have to be updated accordingly.
- R8053: change "unique identifier for the alert event message" to "unique identifier of the alert event message"
- R8056: OBR-7 has to be changed to OBR-3
- General Remark to this kind of requirements in section 4.4.7.1 - 4.4.7.8: To the best of my knowledge, as the different types of OBX segments are defined in IHE PCD TF-2, these are non-restrictive clauses, and we should put a comma before "which".
- Move R8059 and R8060 to the Source Identification OBX or merge them with the already existing requirments, respectively.
- R8061: change "export a Event .." to "export an Event"
- Should we a note to teble Table TF-2:B.4.4.7.2.1-115. Date/Time Alert Event Phase Mapping referring to IHE TF-2 table Table B.8.5-4: Event Phase Coordinated Definitions?
- Note in table Table TF-2:B.4.4.7.2.1-115 "Note that when there are more changes than just the Alert Priority, the Alert Event Phase shall be reported as "update"." shall be a requirement with a link into the table.
- For the B.4.4.7.2 Event Identification OBX Segment and Table TF-2:B.4.4.7.2.2-116. OBX Event Identification Mapping - Physiological Alert Event, the alert text can be static and sourced by the AlertConditionDescriptor, or dynamic when the source is changing the alert text (Cause Info). This is missing and also the description what shall be used. This also applies to Table TF-2:B.4.4.7.2.3-117. OBX Event Identification Mapping - Technical Alert Event.
- R8066: IHE TF-2 only supports one source. When there are multiple sources, only the first one should be used!?
- Table TF-2:B.4.4.7.4-120. Alert Event Phase Mapping ff: see Martin's comments: use related to make clear the signals related to a condition are meant.
- R8071: refers to the wrong table and not to the alert phase- should refer to Table TF-2:B.4.4.7.5-122. Alert State Mapping and alert state
- R8073: refers to the wrong table and not to the inactivation state- should refer to Table TF-2:B.4.4.7.6-124. Alert Inactivation State Mapping and inactivation state
- Table TF-2:B.4.4.7.8-128. Alert Types Value Set Mapping need to be updated due to the APKP decision: advisories are no longer limited to @Kind = Other, but to @Priority / @ActualPriority = None.

Updated PDF from Martin with my comments (dep05028): 
[_TF2_Appendix_B4.-.sdpi-supplement.html-comments_MK_v01_Peters_comments-.pdf](https://github.com/IHE/sdpi-fhir/files/10578612/_TF2_Appendix_B4.-.sdpi-supplement.html-comments_MK_v01_Peters_comments-.pdf)

**Comment by ToddCooper** [comment]
@riechkathrin - See Peter's list above for items that you could take on for Appendix B issue resolution

**Comment by AnnaFeiler** [comment]
@ToddCooper, @PeterKranich : Following a discussion with @riechkathrin, I've split the ticket into smaller parts: In the scope of this ticket, she will take care of the list below. The rest was moved to separat issues IHE/DEV.SDPi#157, IHE/DEV.SDPi#25, IHE/sdpi-fhir#321 and IHE/DEV.SDPi#26. 

- R8053: change "unique identifier for the alert event message" to "unique identifier of the alert event message"
- R8056: OBR-7 has to be changed to OBR-3
- General Remark to this kind of requirements in section 4.4.7.1 - 4.4.7.8: To the best of my knowledge, as the different types of OBX segments are defined in IHE PCD TF-2, these are non-restrictive clauses, and we should put a comma before "which".
- Move R8059 and R8060 to the Source Identification OBX or merge them with the already existing requirments, respectively.
- R8061: change "export a Event .." to "export an Event"
- Should we a note to teble Table TF-2:B.4.4.7.2.1-115. Date/Time Alert Event Phase Mapping referring to IHE TF-2 table Table B.8.5-4: Event Phase Coordinated Definitions?
- Table TF-2:B.4.4.7.4-120. Alert Event Phase Mapping ff: see Martin's comments: use related to make clear the signals related to a condition are meant.
- R8071: refers to the wrong table and not to the alert phase- should refer to Table TF-2:B.4.4.7.5-122. Alert State Mapping and alert state
- R8073: refers to the wrong table and not to the inactivation state- should refer to Table TF-2:B.4.4.7.6-124. Alert Inactivation State Mapping and inactivation state

**Comment by riechkathrin** [comment]
Still open issues:

- General Remark to this kind of requirements in section 4.4.7.1 - 4.4.7.8: To the best of my knowledge, as the different types of OBX segments are defined in IHE PCD TF-2, these are non-restrictive clauses, and we should put a comma before "which".

- Move R8059 and R8060 to the Source Identification OBX or merge them with the already existing requirments, respectively.

- Should we a note to teble Table TF-2:B.4.4.7.2.1-115. Date/Time Alert Event Phase Mapping referring to IHE TF-2 table Table B.8.5-4: Event Phase Coordinated Definitions?

- Table TF-2:B.4.4.7.4-120. Alert Event Phase Mapping ff: see Martin's comments: use related to make clear the signals related to a condition are meant.

**Comment by riechkathrin** [comment]
Still open issues:

- Table TF-2:B.4.4.7.4-120. Alert Event Phase Mapping ff: see Martin's comments: use related to make clear the signals related to a condition are meant.
