### ISSUE TITLE
DDES acronym not well rendered

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#294]
## Section Number

10.4.2.4 & 11.4.2.3

## Priority

Low

## Issue

DDES acronym not well rendered. 

## Proposed Change

Correct (append with a ">" in asciidoc).

**Comment by ToddCooper** [comment]
This issue was actually a left over attempt to craft some "forward definitions" or declarations that can be used in sections of the document BEFORE they are defined.  In this case, use case labels and acronyms.  For SDPi 1.0, most of the definitions were "hard wired" to get the document out by 22 December; however, this DDES instance was overlooked.  

Given that this was a general issue that needed to be addressed, namely forward definitions / declarations, a new file was added to the AsciiDoc root folder - forward-declarations.adoc - and the earlier labels were migrated from the end of the glossary appendix to this new document.  

Additionally, variables were used (e.g., :var_label_use_case_acronym: DDES) as opposed to the previous unsuccessful attempt to use ID attributes (e.g., [[acronym_ddes,DDES]] as is used in the Glossary).  The benefit of the variables - though they are not redefined / vary later in the document - is that they get expanded in section names.  Which was the specific problem this comment was addressing.

Note:  Updates were made for all profile use case sections.

NOT: Updated was the TF-1 Appendix C detailed sections.  This can be a later exercise.
