### ISSUE TITLE
Transaction message names vs. transport layer message names

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/sdpi-fhir#299]
## Section Number

TF-2 Clause 3

## Priority

Medium

## Issue

Using the same names for the generic messages in the transaction as the are in (M)DPWS is confusion. 

## Proposed Change

We could think about introducing a prefix that clarifies this, e.g., GS for "Generic SOMDS", incarnating to GS-Hello/GsHello/GSHello or GS-ProbeMatch/GsProbeMatch/GSProbeMatch. Maybe "SOMDA generic" -> SG. CamelCase looks not that bad: SgHello, SgProbeMatch

**Comment by ToddCooper** [comment]
Yeah, this is also rooted in wanting to have abstract "generic" messages in BICEPS & SOMDS that then get magically mapped to concrete implementation messages in SOMDS & MDPWS.  Coming up with a consistent generalization that matches the abstract side is a VERY GOOD IDEA, as long as it makes since in the BICEPS & SOMDS side of things.  (which is also the TF-1 to TF-2 interaction.

**Comment by ToddCooper** [comment]
Confirmed as deferred to 1.x on Friday call 03.02.2023
