### ISSUE TITLE
pm:Translation mapping

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#349]
## Section Number

Table TF-2:B.3.4.2.7-71. PID-10 Race Mapping

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

In PID-10/CWE-4 and PID-10/CWE-6 only the first entry of the pm:Translation list is mapped. @PeterKranich: I don't really understand your answer to MArtin's comment. If pm:Translation is defined as 0... unbounded, why do we only map the first entry?

**Comment by AnnaFeiler** [comment]
derived from #288

**Comment by PeterKranich** [comment]
> In PID-10/CWE-4 and PID-10/CWE-6 only the first entry of the pm:Translation list is mapped. @PeterKranich: I don't really understand your answer to MArtin's comment. If pm:Translation is defined as 0... unbounded, why do we only map the first entry?
@AnnaFeiler: sorry, I misunderstood Martin's comment first. He meant to add a general requirement for such situations. Well, I'm not a fan of such generalization since a.) there might be a situation where this is not true and then has to "override" the general requirment, and b.) it is more clear to define it case by case.

**Comment by AnnaFeiler** [comment]
Rephrase  "shall be mapped" to "is mapped" and leave the rest of the content as is.
